server:
    port: 8080



datasource:
  url: localhost:3306/userinfo
  
  file_http_url: http://127.0.0.1:9018/ #nginx Url
  file_save_path: D:/model/ #nginx local address 
  # local


  # file_http_url: http://52.197.125.74:9018/ #nginx Url
  # file_save_path: /home/ubuntu/model/ #nginx local address

spring:
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，两位小数
  
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/userinfo
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 553751375
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000
  
  servlet:
    multipart:
      max-file-size: 251658240



mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.cloudisk.demo1.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  # mapper-locations: # mapper映射文件位置
  #   - classpath:mapper/*.xml